# Generated by Django 4.2.7 on 2023-12-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_result_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='model_solution',
            field=models.TextField(default=''),
        ),
    ]
