# Generated by Django 4.2.7 on 2023-12-05 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_testcasegenerator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasegenerator',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem'),
        ),
    ]
